#ckan-client config file
[ckan]
url=https://ckan.example.com
organization=EXAMPLARY_ORGANIZATION
api_token=CKAN_API_TOKEN

[sftp]
server_address=ckan.example.com
server_web_port=8443
username=example_user
private_key=/home/user/.ssh/id_rsa

